### ISSUE TITLE
BE code review 

### ISSUE THREAD

**Issue by hurricanenara** [Ahmadhasanali/krusty-crab-server#5]
great job overall! leaving a few comments for you and your team to read over & implement! let me know if there are any questions :)

1. oops! we should never be pushing .`env` go github! please gitignore this file
https://github.com/Ahmadhasanali/krusty-crab-server/blob/c140ca64c6165126470c7a7b6a7b474ffac4ca3a/.env#L1

2. you're using the unnamed exporting method so the naming is not needed! you can just export the model out like `module.exports = mongoose.model("bills", billSchema)` since when you import this in other files, you can name it however you want (hence unnamed export)
https://github.com/Ahmadhasanali/krusty-crab-server/blob/c140ca64c6165126470c7a7b6a7b474ffac4ca3a/models/invoiceModel.js#L37-L39

3. nit-picky comment here, but we should make sure to not commit/push empty lines like this if not necessary :)
https://github.com/Ahmadhasanali/krusty-crab-server/blob/c140ca64c6165126470c7a7b6a7b474ffac4ca3a/models/userModel.js#L9

4. i'm curious how you decided to create an instance of the invoice first, then save it -- it's not incorrect, but if there is a simpler way (convention) it's best to stick with it! for example, using the `.create` method directly on the Invoice model
https://github.com/Ahmadhasanali/krusty-crab-server/blob/c140ca64c6165126470c7a7b6a7b474ffac4ca3a/routes/invoiceRoutes.js#L8-L9

5. we should improve this error handling! the developer will see the error in their console, but what about the user? what error should we send to the user to communicate with them that there was an internal network error?
https://github.com/Ahmadhasanali/krusty-crab-server/blob/c140ca64c6165126470c7a7b6a7b474ffac4ca3a/routes/invoiceRoutes.js#L23

**Comment by refido** [comment]
Okay thanks for the review, the issue will be revised in the next pull request.
